version: 0.0
os: linux 
files:
  - sources: /https://console.aws.amazon.com/s3/buckets/codepipeline-us-east-1-441242651481?region=us-east-1&prefix=express-app-pipeline/
    destination: /home/ec-2-user/express-app
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: ec2-user
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ec2-user

